version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
init:
- cmd: >-
    @echo off

    for /f %%a in ('powershell -Command "Get-Date -format yy.MM.dd.HHmm"') do set BUILD_VERSION=%%a

    echo Build Version: %BUILD_VERSION%
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BUILD_VERSION)
  assembly_file_version: $(BUILD_VERSION)
  assembly_informational_version: $(BUILD_VERSION)
environment:
  BUILD_VERSION: 0.0.0.0
before_build:
- cmd: >-
    echo Build Directory: %APPVEYOR_BUILD_FOLDER%

    nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
before_package:
- cmd: >-
    echo Inject build version %BUILD_VERSION% in nuget manifest...

    powershell -Command "(get-content -Path %APPVEYOR_BUILD_FOLDER%\WpfHelpers\WpfHelpers.nuspec) | foreach-object {$_ -replace '0.0.0.0', '%BUILD_VERSION%'} | set-content %APPVEYOR_BUILD_FOLDER%\WpfHelpers\WpfHelpers.nuspec"

    type %APPVEYOR_BUILD_FOLDER%\WpfHelpers\WpfHelpers.nuspec

    powershell -Command "(get-content -Path %APPVEYOR_BUILD_FOLDER%\Licensing\Licensing.nuspec) | foreach-object {$_ -replace '0.0.0.0', '%BUILD_VERSION%'} | set-content %APPVEYOR_BUILD_FOLDER%\Licensing\Licensing.nuspec"

    type %APPVEYOR_BUILD_FOLDER%\Licensing\Licensing.nuspec
deploy:
- provider: NuGet
  api_key:
    secure: FprWChvPzyBTf15roCDBXtHgL/XkekHWTWHohvO1JZjwD948yYGstm8LnFeb0W6I
  skip_symbols: true
  on:
    branch: master